# coding: utf-8

"""
    Catapult REST Endpoints

    OpenAPI Specification of catapult-rest

    The version of the OpenAPI document: 1.0.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NetworkTypeEnum(int, Enum):
    """
    Network type: * 0x60 (96 decimal) - Mijin network. * 0x90 (144 decimal) - Mijin test network. * 0x68 (104 decimal) - Main network. * 0x98 (152 decimal) - Test network. 
    """

    """
    allowed enum values
    """
    NUMBER_96 = 96
    NUMBER_144 = 144
    NUMBER_104 = 104
    NUMBER_152 = 152

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NetworkTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


