name: Publish Python Package to PyPI

on:
  push:
    branches:
      - pypi

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python
        run: uv python install 3.12

      - name: Build
        run: uvx --from build pyproject-build --installer uv
        working-directory: ./python

      - name: Publish PyPI
        run: uvx twine upload dist/*
        working-directory: ./python
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
